version: '3'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: jitsi/etherpad:stable-4627-1
        restart: ${RESTART_POLICY}
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
